apiVersion: apps/v1
kind: Deployment
metadata:
  name: infotrack-search-engine-webapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infotrack-search-engine-webapi
  template:
    metadata:
      labels:
        app: infotrack-search-engine-webapi
    spec:
      containers:
      - name: infotracksalessearchenginewebapi
        image: lukasnguyen2908/infotracksalessearchenginewebapi:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          - name: ASPNETCORE_HTTP_PORTS
            value: "80"
          - name: GoogleBaseAddress
            valueFrom:
              configMapKeyRef:
                name: infotrack-search-engine-webapi-configmap
                key: google_base_address
          - name: BingBaseAddress
            valueFrom:
              configMapKeyRef:
                name: infotrack-search-engine-webapi-configmap
                key: bing_base_address
          - name: InfotrackWebAppBaseAddress
            valueFrom:
              configMapKeyRef:
                name: infotrack-search-engine-webapi-configmap
                key: infotrack_webapp_base_address
          - name: GoogleSearch__ClassesContainUrl
            valueFrom:
              configMapKeyRef:
                name: infotrack-search-engine-webapi-configmap
                key: google_search_classes_contain_url
          - name: GoogleSearch__NumbersOfSearchResults
            valueFrom:
              configMapKeyRef:
                name: infotrack-search-engine-webapi-configmap
                key: google_search_numbers_of_search_results
          - name: ConnectionStrings__SearchEngineDatabase
            valueFrom:
              secretKeyRef:
                name: infotrack-search-engine-sqlserver-secret
                key: connection_string
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: infotrack-search-engine-webapi-service
spec:
  type: NodePort
  selector:
    app: infotrack-search-engine-webapi
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 80
    nodePort: 31000